### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by i68040** [raptorswing/Qt-Socks-Server#7]
Is this LGPL or BSD licensed perchance? I just want to make sure I'm using your code in a way that respects your rights. :)

Edit: Looks like you are distributing one of your other projects as BSD: https://github.com/raptorswing/MapGraphics/blob/master/LICENSE

**Comment by blochbergermax** [comment]
Doesn't the commit c597acb4ec8d42ec5dc063908539f1df85dacbd8 fix this issue?

**Comment by raptorswing** [comment]
Yes, you're right.
